### ISSUE TITLE
On-Premise Connector never re-connects to Server after Server is restarted

### ISSUE THREAD

**Issue by jasminsehic** [thinktecture/relayserver#134] opened 2019-02-02 01:20 UTC
### Actual behavior
If a connector application is running and the server is restarted due to upgrade or failover between load balanced server instances, the connector application gets stuck somehow trying to post to server and throwing exception. See [relayserver connector error after server restart.txt](https://github.com/thinktecture/relayserver/files/2823861/relayserver.connector.error.after.server.restart.txt) for log file containing the exceptions. Only way to get connector to re-connect to server is to restart the connector application. Once connector app is restarted it connects to server fine.

### Expected behavior
I expect the connector application would self-recover after the server has been restarted and would not need the connector application to be restarted.

### Steps to reproduce
1. Start server then start connector application, make sure it is connected to server and that you can relay some messages to client.
2. Stop server for 5 minutes and restart the server. Don't restart the connector application, make sure that keeps running. 
3. See that once the server is up and running again that the connector repeatadly throws exceptions about posting to relay

```
2019-02-02 02:51:13.984 WARN | Unhandled request. connection-id="591a8de3-b8c7-42aa-a81f-861149b073a3", message=[[[]], [[]], [[]], [[]], [[]], [[]], [[]], [[[[]]]], [[]], [[]], [[]]]
2019-02-02 02:51:24.218 ERROR | Error during posting to relay. connection-id="591a8de3-b8c7-42aa-a81f-861149b073a3"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thinktecture.Relay.OnPremiseConnector.SignalR.RelayServerConnection.<SendToRelayAsync>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thinktecture.Relay.OnPremiseConnector.SignalR.RelayServerConnection.<PostResponseAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Thinktecture.Relay.OnPremiseConnector.SignalR.RelayServerConnection.<OnMessageReceived>d__57.MoveNext()
2019-02-02 02:51:43.125 ERROR | Error during posting to relay. connection-id="591a8de3-b8c7-42aa-a81f-861149b073a3"
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thinktecture.Relay.OnPremiseConnector.SignalR.RelayServerConnection.<SendToRelayAsync>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thinktecture.Relay.OnPremiseConnector.SignalR.RelayServerConnection.<PostResponseAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Thinktecture.Relay.OnPremiseConnector.SignalR.RelayServerConnection.<OnMessageReceived>d__57.MoveNext()
```

### Version
Server is latest develop sha b494205 commit
Connector is v2.0.0 from NuGet

**Comment by jasminsehic** [comment] 2019-02-02 07:31
This patch seems to solve the above problem, but maybe there is a better way to handle it @gingters?
```
diff --git a/Thinktecture.Relay.OnPremiseConnector/SignalR/RelayServerConnection.cs b/Thinktecture.Relay.OnPremiseConnector/SignalR/RelayServerConnection.cs
index a6a956d..9c3d360 100644
--- a/Thinktecture.Relay.OnPremiseConnector/SignalR/RelayServerConnection.cs
+++ b/Thinktecture.Relay.OnPremiseConnector/SignalR/RelayServerConnection.cs
@@ -340,6 +340,9 @@ namespace Thinktecture.Relay.OnPremiseConnector.SignalR
 			catch (Exception ex)
 			{
 				_logger?.Error(ex, "Error during handling received message. connection-id={ConnectionId}, message={Message}", ConnectionId, message);
+
+				if (ex is TaskCanceledException)
+					Reconnect();
 			}
 			finally
 			{
@@ -365,6 +368,9 @@ namespace Thinktecture.Relay.OnPremiseConnector.SignalR
 					catch (Exception ex)
 					{
 						_logger?.Error(ex, "Error during posting unhandled request response to relay. request-id={RequestId}", request.RequestId);
+
+						if (ex is TaskCanceledException)
+							Reconnect();
 					}
 				}
 			}

```

**Comment by gingters** [comment] 2019-02-04 13:05
I'm sorry, but we really can't reproduce this problem.

I spend a few hours today to test it and I tried every officially released connector version (from the tags `v1.0.4`, `2.0.0` and `2.1.0`), with 2 active connectors per version connecting to a server. I tested this combination with a server from the `2.0.0` tag as well as the new `2.1.0` tag.

I followed your steps starting the server and the connectors. I then relayed a few requests through every connector. I shut down the server for some time (tried a few seconds, several minutes, over 5 minutes and even up to 10 minutes). All connectors were running all the time. After starting the server again, all connectors were able to successfully reconnect to the server without any issue, every single time.

Do you have further instructions that could help us reproduce this behaviour?

**Comment by jasminsehic** [comment] 2019-02-04 13:55
Hi @gingters only thing I can think of is that I am going through a load balancer but not sure how that would cause an issue.

**Comment by jasminsehic** [comment] 2019-02-04 14:50
@gingters I can get you to connect to a test server I have behind a load balancer and coordinate a server restart so you can see the unrecoverable exceptions start in the connector. Would that help?

**Comment by gingters** [comment] 2019-02-05 13:41
Its difficult to debug if I don't have the server in debugging too (correlating requests etc.).

Based on the logs, it seems the OPC has a stable SignalR connection to the server, and the actual issue is with the Http POST calls that answer the requests and sends the responses back to the RelayServer besides the SignalR channel.

Based on that, I don't understand how your PR would fix this issue: It forces disconnecting and re-connecting the SignalR connection only, and does not do anything to the HttpClient which has the real issues posting to the RelayServer.

**Comment by gingters** [comment] 2019-02-05 13:47
What I suspect, - but at the moment I can't prove that - is that the HttpClient has, due to keepalive, an active tcp connection to the LB. The LB loses the other part of that connection to the RelayServer, but somehow does not notice that (or does, but can't do anything about it).

After the RelayServer comes back, the SignalR connection is re-instantiated, but the HttpClient still uses the existing, but broken TCP connection to the LB to post its data. These requests never reach the RelayServer.

So, reconnecting via SignalR won't really help. I rather guess disposing and recreating the HttpClient would. I really don't understand why your changes solve the issue for you. That should not be possible. 🤔

**Comment by jasminsehic** [comment] 2019-02-05 14:53
I think I follow you. I will do some tests to confirm what is happening, you’ve given me some ideas.

**Comment by jasminsehic** [comment] 2019-02-06 13:18
Reconnecting SignalR actually gets a new bearer token and sets it for HttpClient but I don’t think that fixes it. I looked at this in more detail this evening and found that when I used Fiddler to monitor the HttpClient heartbeat response all of a sudden exceptions stopped. Stopping Fiddler the exceptions resumed. Will dig a bit more.

**Comment by gingters** [comment] 2019-02-08 14:45
I still cannot reproduce this issue. However, I tried to work on what I think could be the problem.
Could you please try the changes in the OPC I commited to the `bugfix/brokenConnections` branch ?
In case of timeouts, this will create a new `HttpClient` instance and re-try the last request with that new client, as well as use that new client from there on.

I would be a lot happier when I could reproduce the issue and check myself if that really helps instead of just guessing and making such change in the dark, but this is a difficult thing here.

**Comment by jasminsehic** [comment] 2019-02-09 04:31
Yes I will try this and let you know the results

**Comment by gingters** [comment] 2019-02-19 09:18
Hi Jasmin, did you have any chance to check whether that helped?

**Comment by jasminsehic** [comment] 2019-02-19 09:24
Hi @gingters I had a good look at this over last few nights, I will write up a summary shortly.

**Comment by jasminsehic** [comment] 2019-02-19 13:38
OK, first I want to say thank you for looking into this and apologies for the delay in response, I have been travelling.

Just some background to explain the environment at question. RelayServer is hosted on AWS and we rely on ALB (Application Load Balancer) to direct traffic to one or many RelayServer EC2 instances which auto-scale based on demand. SQL database is hosted in RDS. At the moment we only have one EC2 instance as the load is not high. 

The scenario where I saw the issue initially happen is when we either upgraded RelayServer server application or we upgraded the Windows OS. In either case we launch a new EC2 AMI (with new OS version) and deploy RelayServer server application on it, wait for it to start up and be in position to receive requests before we shutdown the old EC2 instance. This way we have zero downtime of the service as the ALB automatically redirects requests from old to new EC2 instance. In this transition what seems to happen is that the HTTP requests using `HttpClient` start failing from connector side however strangely the SignalR connection seems to continue working, you saw this before from logs. Only way to get the HTTP requests via `HttpClient` working again is to restart the connector application. This indicates that somehow the ALB is not routing traffic to the new EC2 instance for HTTP request with `HttpClient` but for SignalR connection it is. 

First I tried using your `bugfix/brokenConnections` branch. I deployed a connector with that implementation and then scheduled a Windows OS upgrade on server side and waited for the switch-over. During the switch-over period the connector started failing and the implementation started to re-create the `HttpClient` as expected but this did not resolve the situation. I've attached a log file so you can see what happened. 
[RelayServerConnector_2019-02-19.0.log](https://github.com/thinktecture/relayserver/files/2880017/RelayServerConnector_2019-02-19.0.log)

At this point I reverted to my previous branch with `Reconnect()` fix, deployed a connector with this and scheduled another Windows OS upgrade on the server side. To my surprise the connector started failing to send HTTP requests again and reconnect attempt did not fix the problem. 

Now I realised that the steps to reproduce the problem I provided before were missing one key ingredient which is that the servers I was using for testing had actually apps being connected to it and it had some load. Since they were being used that potentially was increasing the chance of the problem happening and that earlier when I was testing and reproducing the problem perhaps there were no apps connecting (maybe less or no load) I was not considering this so I assumed that because I couldn't reproduce the problem with my `Reconnect()` fix that I fixed it, it turns out it was likely just lucky (or unlucky) timing. So now I have a test app running in the background sending a web request every 5 seconds to generate some load all the time to re-produce the issue all the time.

So starting with a clean slate ... one thing I can 100% confirm is that each time this problem occurs that restarting the connector application fixes the problem 100% of the time. I focused on this to understand how `HttpClient` works and found out something interesting that could possibly explain some part of the issue. I used Wireshark to compare the TCP traffic I noticed that the connector application did not close the TCP connection fully even when `HttpClient` was disposed in your branch, whereas when the connector application was closed the TCP connection was fully closed. This however did not explain two things, 1) why does disposing `HttpClient` not close the TCP connection fully and 2) why does ALB not simply start directing traffic to the new EC2 instance.

On 1) I found this article http://www.nimaara.com/2016/11/01/beware-of-the-net-httpclient/ which lead me to https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepoint.connectionleasetimeout?view=netstandard-2.0 which talks about setting this to something less than infinite to ensure the connection is regularly closed to ensure load balanced scenarios are managed. This then lead me to 2) which implies that ALB will only potentially look at routing `new` requests to the new EC2 instance and that the existing connections that stay open and get re-used would never be directed to the EC2 instance. I suspect this is due to HTTP 1.1 Keep Alive. It sounded like using ConnectionLeaseTimeout could solve the problem so I implemented a patch (see below) to try this on top of your branch. I deployed a new connector with this patch, scheduled a Windows OS upgrade on the server side, started an app to sent requests every 5 seconds. And when the switch over happened it seemed to transition correctly and start routing the HTTP requests to the correct EC2 instance. 

I still want to do more testing and I am not sure this is 100% the solution, I am still not sure I understand the ALB behaviour fully in how it re-uses connections (maybe this is not documented) and I have lots of questions around idle timeout settings on connector side, on ALB side and on server side to set this up correctly (i.e. possibly the idle timeout on the server side can't be lower than on the ALB side).

So not 100% solved just yet, but have better understanding of where the problem could be, and I will keep looking into it. Hopefully this also gives you an idea on where the issue could be or what a proper solution could be.

```
diff --git a/Thinktecture.Relay.OnPremiseConnector/SignalR/RelayServerHttpConnection.cs b/Thinktecture.Relay.OnPremiseConnector/SignalR/RelayServerHttpConnection.cs
index ee287f4..942f2d8 100644
--- a/Thinktecture.Relay.OnPremiseConnector/SignalR/RelayServerHttpConnection.cs
+++ b/Thinktecture.Relay.OnPremiseConnector/SignalR/RelayServerHttpConnection.cs
@@ -1,4 +1,5 @@
 using System;
+using System.Net;
 using System.Net.Http;
 using System.Net.Http.Headers;
 using System.Threading;
@@ -22,6 +23,11 @@ namespace Thinktecture.Relay.OnPremiseConnector.SignalR
 			_relayServerUri = relayServerUri ?? throw new ArgumentNullException(nameof(relayServerUri));
 			_requestTimeout = requestTimeout;
 
+			// to handle load balancer changes and DNS changes
+#if NETSTANDARD2_0
+			ServicePointManager.FindServicePoint(relayServerUri).ConnectionLeaseTimeout = requestTimeout.Milliseconds;
+			ServicePointManager.DnsRefreshTimeout = requestTimeout.Milliseconds;
+#endif
 			CreateHttpClient();
 		}
 
````

**Comment by gingters** [comment] 2019-04-02 08:27
Hi Jasmin, do you have any new information on that?

I incorporated your change in the branch, and I changed the exception type to react upon to recreate the http client, because I thought maybe I missed the actual exception type that caused the issue.

Caution: The branch `bugfix/brokenConnections` was force-pushed because I rebased it on the latest develop.

**Comment by jasminsehic** [comment] 2019-04-02 16:17
Hi @gingters 
I haven't spent more time on this unfortunately, I ran into an issue with lost connections somehow where the entire RelayServer would stop accepting connections, could be related to some of the other fixes I see you have now merged as well. 
I will try now with all the latest changes you have in develop and see if that is more stable.

**Comment by jasminsehic** [comment] 2019-04-08 05:02
Hi @gingters I just did some testing over the weekend and with the ServicePointManager changes using .NET Standard 2.0 the client automatically recovers the connection when I upgrade the EC2 instance behind an ELB/ALB on AWS. Thanks for putting this in!

**Comment by jasminsehic** [comment] 2019-05-16 01:45
@gingters for reference I have completed and released the custom code that includes Memcached as a temporary store and support for Forwarded HTTP Header RFC 7239. See https://github.com/jasminsehic/relayserver-custominterceptors

**Comment by gingters** [comment] 2019-09-09 09:10
#146 has been merged and will be released soon-ish. Closing here.

**Closed by gingters** 2019-09-09 09:10 UTC

**Comment by jasminsehic** [comment] 2019-09-09 10:50
Thanks @gingters
