### ISSUE TITLE
ManagementWeb: 401 directly after login, tested with 2.2.0, 2.1.2

### ISSUE THREAD

**Issue by fuse314** [thinktecture/relayserver#147] opened 2019-07-17 09:27 UTC
### Actual behavior
After installing RelayServer, I tried to set up a new link in the managementweb. The browser shows "name already taken", in the DevTools console, I can see lots of 401 requests.

Right after the login, I see two requests:
token => 200 ok (containing the token)
info => 401 unauthorized (token is in header)
![image](https://user-images.githubusercontent.com/927896/61364206-a989ae00-a885-11e9-9213-491d89363ed4.png)

I tried with the releases 2.2.0 and 2.1.2, they show the same behaviour.

### Expected behavior
Login in managementweb should work as expected.

### Steps to reproduce

1. Install new Instance of RelayServer (we used a new MSSQL-DB for each test)
2. Set up new user
3. Login with user
4. Click on "Links" or "Users" (or navigate anywhere else...) -> the login screen is shown again

### Version
- release 2.2.0
- release 2.1.2

**Comment by gingters** [comment] 2019-07-17 14:08
Hi Gottfried,

thanks for bringing that up. Seems I missed that bit when updating the documentation the last time.
Sorry for the inconvenience.

With the default configuration, the issue is that the issued security token is signed with a value that gets lost when the server tries to verify it the next time it is presented to the management web api.

To solve this problem, please configure a `SharedSecret` in the RelayServer configuration.
That needs to be a base64 encoded value of a secret string.

Example: `DasIstEinSharedSecretDasHoffentlichGeheimBleibt` would be encoded to `RGFzSXN0RWluU2hhcmVkU2VjcmV0RGFzSG9mZmVudGxpY2hHZWhlaW1CbGVpYnQ=` and that needs to go in the config.

After that, you should stay logged in.

**Comment by gingters** [comment] 2019-07-17 14:12
We need to address that in the documentation first.
Then, we could write a warning in the log when the value is empty on server startup.

We don't want to ship a default value in the sample / starting config, because then all RelayServer installations would be productive with the same shared secret and everybody could generate a security token that would work with every installation that did not change the value.

**Comment by fuse314** [comment] 2019-07-18 12:45
Thank you, I can confirm managementweb working correctly after setting a SharedSecret in the .config file.
- A Error message would be very helpful
- Even better: the server could create a random string if no SharedSecret was set (this needs write access to the .config file, though...)
- As you already suggested: the (installation-) documentation needs to address this.

**Comment by gingters** [comment] 2019-07-18 12:52
Glad that helped.

Auto-generating a random value is tricky, because that could lead to strange behavior if the RelayServer is used in a load-balanced or scaled-out environment. All RelayServer instances needs to share the same secret (hence sharedSecret ;) ), and if they don't it could happen that some requests from the management web work, but some don't (as they get to the other instance with a different secret), or even worse, some OnPremiseConnectors would connect and some won't, as they also use a token signed with this value.

We'll think about that, maybe we could use a random value only when no file store is configured, which means the server is definitely not in a loadbalanced/scaled out environment.

We'll keep this issue open until the docs / warning is resolved at least.

**Comment by gingters** [comment] 2019-09-09 10:31
Fix has been merged and will be released with 2.3.0 soon-ish. Closing here.

**Closed by gingters** 2019-09-09 10:31 UTC
Labels: documentation, enhancement, question
